<table class="table table-hover table-bordered">
    {{-- Details --}}
    <tr class="bg-gray">
        <th colspan="2">{{ trans_choice('core.detail', 2) }}</th>
    </tr>
    <tr>
        <td>{{ trans_choice('core.contact', 1) }} {{ trans_choice('core.type', 1) }}</td>
        <td>@{{ client_types[contact_type] }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('core.contact', 1) }} {{ trans_choice('core.name', 1) }}</td>
        <td>@{{ contact.name }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('core.external_id', 1) }}</td>
        <td>
            <span v-if="external_id">@{{ external_id }}</span>
            <span v-else>{{ trans('loan::general.to_be_autogenerated') }}</span>
        </td>
    </tr>
    <tr>
        <td>{{ trans_choice('core.location', 1) }}</td>
        <td>@{{ business_location.name }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.loan_product', 1) }}</td>
        <td>@{{ product.name }}</td>
    </tr>

    {{-- Terms --}}
    <tr class="bg-gray">
        <th colspan="2">{{ trans_choice('core.term', 2) }}</th>
    </tr>
    <tr>
        <td>{{ trans_choice('core.principal', 1) }}</td>
        <td>@{{ currency.code }} @{{ number_format(applied_amount) }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.interest', 1) }} {{ trans_choice('loan::general.rate', 1) }}</td>
        <td>@{{ number_format(interest_rate) }}% {{ strtolower(trans('core.per')) }} @{{ interest_rate_type }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('core.loan', 1) }} {{ trans_choice('core.term', 1) }}</td>
        <td>@{{ loan_term }} @{{ loan_term_label(loan_term) }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.repayment', 1) }} {{ trans_choice('loan::general.frequency', 1) }}</td>
        <td> {{ trans('loan::general.every') }} @{{ repayment_frequency }} @{{ loan_term_label(loan_term) }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.expected', 1) }} {{ trans_choice('loan::general.disbursement', 1) }}
            {{ trans_choice('core.date', 1) }}</td>
        <td>@{{ expected_disbursement_date }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('core.loan_officer', 1) }}</td>
        <td>@{{ loan_officer.user_full_name }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.expected', 1) }} {{ trans_choice('loan::general.first_payment_date', 1) }}</td>
        <td>@{{ expected_first_payment_date }}</td>
    </tr>

    {{-- Settings --}}
    <tr class="bg-gray">
        <th colspan="2">{{ trans_choice('core.setting', 2) }}</th>
    </tr>
    <tr>
        <td>{{ trans_choice('core.loan', 1) }} {{ trans_choice('loan::general.purpose', 1) }}</td>
        <td>@{{ loan_purpose.name }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.loan_officers_to_approve_loan', 1) }}</td>
        <td>@{{ loan_approval_officers_chosen }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.grace_on_principal_paid', 1) }}</td>
        <td>@{{ grace_on_principal_paid }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.grace_on_interest_paid', 1) }}</td>
        <td>@{{ grace_on_interest_paid }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.grace_on_interest_charged', 1) }}</td>
        <td>@{{ grace_on_interest_charged }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.interest_methodology', 1) }}</td>
        <td>@{{ capitalize_first_letter(interest_methodology) }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.amortization_method', 1) }}</td>
        <td>@{{ amortization_method_chosen }}</td>
    </tr>
    <tr>
        <td>{{ trans_choice('loan::general.loan_transaction_processing_strategy', 1) }}</td>
        <td>@{{ loan_transaction_processing_strategy.name }}</td>
    </tr>
</table>
