<?php

return [
    'sidebar' => [
        [
            'name' => 'Dashboard',
            'order' => 1,
            'target' => '',
            'icon' => 'bi bi-speedometer2',
            'route' => null,
            'url' => null,
            'vue_route' => "#/",
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Home page',
            'order' => 2, 
            'target' => '_blank',
            'icon' => 'bi bi-house',
            'route' => 'frontend',
            'url' => null,
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Tickets',
            'order' => 3, 
            'target' => '',
            'icon' => 'bi bi-list-ul',
            'route' => 'dashboard.tickets',
            'url' => null,
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Articles',
            'order' => 4, 
            'target' => '',
            'icon' => 'bi bi-newspaper',
            'route' => null,
            'url' => null,
            'vue_route' => "#/articles",
            'sub_items' => [],
            'permissions' => ['manage_articles'],
        ],
        [
            'name' => 'Categories',
            'order' => 5, 
            'target' => '',
            'icon' => 'bi bi-folder',
            'route' => null,
            'url' => null,
            'vue_route' => "#/categories",
            'sub_items' => [],
            'permissions' => ['manage_categories'],
        ],
        [
            'name' => 'Saved replies',
            'order' => 6, 
            'target' => '',
            'icon' => 'bi bi-reply-all',
            'route' => null,
            'url' => null,
            'vue_route' => "#/saved_replies",
            'sub_items' => [],
            'permissions' => ['create_saved_reply'],
        ],
        [
            'name' => 'Customers',
            'order' => 7, 
            'target' => '',
            'icon' => 'bi bi-people',
            'route' => null,
            'url' => null,
            'vue_route' => "#/customers",
            'sub_items' => [],
            'permissions' => ['manage_customers'],
        ],
        [
            'name' => 'Employees',
            'order' => 8, 
            'target' => '',
            'icon' => 'bi bi-person-check',
            'route' => null,
            'url' => null,
            'vue_route' => "#/employees",
            'sub_items' => [],
            'permissions' => ['manage_employees'],
        ],
        // [
        //     'name' => 'Modules',
        //     'target' => '',
        //     'icon' => 'bi bi-boxes',
        //     'route' => null,
        //     'url' => null,
        //     'vue_route' => "#/modules",
        //     'sub_items' => [],
        //     'permissions' => ['list_modules'],
        //     'order' => 9
        // ],
        "settings" => [
            'name' => 'Settings',
            'label' => 'Settings',
            'order' => 10, 
            'target' => '',
            'icon' => 'bi bi-sliders',
            'route' => 'dashboard.settings',
            'url' => null,
            'vue_route' => null,
            'permissions' => ['view_settings'],
            'sub_items' => null,
        ],

        // [
        //     'name' => 'Customer Groups',
        //     'order' => 11, 
        //     'target' => '',
        //     'icon' => 'bi bi-people',
        //     'route' => null,
        //     'url' => null,
        //     'vue_route' => "#/customer-groups",
        //     'sub_items' => [],
        //     'permissions' => [],
        // ],

        // [
        //     'name' => 'Employee Groups',
        //     'order' => 12, 
        //     'target' => '',
        //     'icon' => 'bi bi-person-check',
        //     'route' => null,
        //     'url' => null,
        //     'vue_route' => "#/employee-groups",
        //     'sub_items' => [],
        //     'permissions' => [],
        // ],

        // [
        //     'name' => 'Notification Module',
        //     'order' => 14, 
        //     'target' => '',
        //     'icon' => 'bi bi-bell',
        //     'route' => null,
        //     'url' => null,
        //     'vue_route' => "#/bulk-notifications",
        //     'sub_items' => [],
        //     'permissions' => [],
        // ],
        
        // [
        //     'name' => 'Update Storage',
        //     'order' => 15, 
        //     'target' => '',
        //     'icon' => 'bi bi-folder',
        //     // 'route' => 'create-symlink',
        //     'route' => 'dashboard',
        //     'url' => null,
        //     'vue_route' =>null,
        //     'sub_items' => [],
        //     'permissions' => [],
        // ],
    ]
];