INSERT INTO specializations (name, description) VALUES
('Cardiologist', 'Specializes in diagnosing and treating heart conditions and diseases.'),
('Dermatologist', 'Focuses on skin, hair, and nail disorders.'),
('Neurologist', 'Expert in treating disorders of the nervous system, including the brain and spinal cord.'),
('Pediatrician', 'Provides medical care for infants, children, and adolescents.'),
('General Practitioner', 'Offers general healthcare services and basic treatment for a wide variety of health issues.'),
('Oncologist', 'Specializes in the diagnosis and treatment of cancer.'),
('Endocrinologist', 'Treats disorders related to hormones and the endocrine system, such as diabetes and thyroid disorders.'),
('Psychiatrist', 'Deals with mental health issues and emotional disorders.'),
('Orthopedic Surgeon', 'Treats musculoskeletal system issues, including bones, joints, and muscles.'),
('Rheumatologist', 'Focuses on autoimmune diseases and arthritis-related conditions.'),
('Ophthalmologist', 'Specializes in eye and vision care, including surgeries.'),
('Gynecologist', 'Focuses on female reproductive health and childbirth.'),
('Urologist', 'Treats urinary tract issues and male reproductive health.'),
('Anesthesiologist', 'Specializes in pain relief during surgery and other procedures.'),
('Gastroenterologist', 'Focuses on the digestive system and related disorders.'),
('Pulmonologist', 'Specializes in respiratory system disorders, including the lungs.'),
('Nephrologist', 'Treats kidney-related issues and diseases.'),
('ENT Specialist', 'Expert in conditions related to the ear, nose, and throat.'),
('Radiologist', 'Uses imaging technologies to diagnose diseases.'),
('Immunologist', 'Specializes in the immune system and related disorders, including allergies and autoimmune diseases.');
